# Generated by Django 4.2.7 on 2025-03-20 16:54

from django.db import migrations, models
import django.db.models.deletion
import establishements.models


class Migration(migrations.Migration):

    dependencies = [
        ('establishements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=establishements.models.upload_to_establishment_pics)),
                ('establishement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishements.establishement')),
            ],
        ),
    ]
