# Generated by Django 4.2.7 on 2025-03-26 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishements', '0005_alter_cuisine_name_alter_restaurant_cuisine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='average_rating',
        ),
    ]
