# Generated by Django 4.2.7 on 2025-03-26 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishements', '0006_remove_hotel_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='name',
        ),
    ]
