# Generated by Django 4.2.7 on 2025-03-26 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('establishements', '0007_remove_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishement',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='establishement', to='accounts.profile'),
        ),
    ]
