# Generated by Django 4.2.7 on 2025-03-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishements', '0008_alter_establishement_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='number',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='number',
            new_name='amount',
        ),
    ]
