# Generated by Django 4.2.7 on 2025-03-27 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishements', '0009_rename_number_room_amount_rename_number_table_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='establishement',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='establishements.establishement'),
            preserve_default=False,
        ),
    ]
