ALGERIAN_CITIES = (
    ("Aïn Beïda", "Aïn Beïda"), ("Oum El Bouaghi", "Oum El Bouaghi"), ("Aïn Oussera", "Aïn Oussera"), ("Bab Ezzouar", "Bab Ezzouar"), ("Baraki", "Baraki"), ("Barika", "Barika"), ("Béchar", "Béchar"),
    ("Berrouaghia", "Berrouaghia"), ("Biskra", "Biskra"), ("Bordj Bou Arréridj", "Bordj Bou Arréridj"), ("Bordj El Kiffan", "Bordj El Kiffan"), ("Bou Saâda", "Bou Saâda"), ("Chlef", "Chlef"), ("Corso", "Corso"),
    ("Djelfa", "Djelfa"), ("El Eulma", "El Eulma"), ("El Khroub", "El Khroub"), ("El Marsa", "El Marsa"), ("El Oued", "El Oued"), ("Flenucleta", "Flenucleta"), ("Floriana", "Floriana"), ("Ghardaïa", "Ghardaïa"),
    ("Guelma", "Guelma"), ("Jijel", "Jijel"), ("Khenchela", "Khenchela"), ("L'Hillil", "L'Hillil"), ("Laghouat", "Laghouat"), ("Larbatache", "Larbatache"), ("Lardjem", "Lardjem"), ("Larhat", "Larhat"),
    ("Lazharia", "Lazharia"), ("Lazrou", "Lazrou"), ("Legata", "Legata"), ("Lemsane", "Lemsane"), ("Les Eucalyptus", "Les Eucalyptus"), ("Lichana", "Lichana"), ("Lioua", "Lioua"), ("M'Chedallah", "M'Chedallah"),
    ("M'Chouneche", "M'Chouneche"), ("M'Cid", "M'Cid"), ("M'Cif", "M'Cif"), ("M'Daourouch", "M'Daourouch"), ("M'Sila", "M'Sila"), ("M'Tarfa", "M'Tarfa"), ("M'Toussa", "M'Toussa"), ("Maadid", "Maadid"),
    ("Maala", "Maala"), ("Maamora", "Maamora"), ("Maaouia", "Maaouia"), ("Maarif", "Maarif"), ("Mâatkas", "Mâatkas"), ("Madna", "Madna"), ("Maghnia", "Maghnia"), ("Magrane", "Magrane"), ("Mahdia", "Mahdia"),
    ("Mahelma", "Mahelma"), ("Makouda", "Makouda"), ("Mansoura", "Mansoura"), ("Mansoura (Ghardaïa)", "Mansoura (Ghardaïa)"), ("Mansoura (Tlemcen)", "Mansoura (Tlemcen)"), 
    ("Mansourah (Mostaganem)", "Mansourah (Mostaganem)"), ("Maoussa", "Maoussa"), ("Marsa Ben M'Hidi", "Marsa Ben M'Hidi"), ("Mascara", "Mascara"), ("Mazouna", "Mazouna"), ("Mécheria", "Mécheria"),
    ("Méchraâ Houari Boumédienne", "Méchraâ Houari Boumédienne"), ("Mechraa Safa", "Mechraa Safa"), ("Mechtras", "Mechtras"), ("Médéa", "Médéa"), ("Mediouna", "Mediouna"), ("Medjana", "Medjana"),
    ("Medjebar", "Medjebar"), ("Medjedel", "Medjedel"), ("Medrissa", "Medrissa"), ("Medroussa", "Medroussa"), ("Mefatha", "Mefatha"), ("Meftah", "Meftah"), ("Megarine", "Megarine"), ("Meghila", "Meghila"),
    ("Mekhadma", "Mekhadma"), ("Mekhatria", "Mekhatria"), ("Mekla", "Mekla"), ("Melaab", "Melaab"), ("Melbou", "Melbou"), ("Mellakou", "Mellakou"), ("Menaâ", "Menaâ"), ("Menaceur", "Menaceur"),
    ("Merahna", "Merahna"), ("Merdja Sidi Abed", "Merdja Sidi Abed"), ("Méridja", "Méridja"), ("Messaâd", "Messaâd"), ("Metarfa", "Metarfa"), ("Metlili", "Metlili"), ("Mezaourou", "Mezaourou"),
    ("Mih Ouensa", "Mih Ouensa"), ("Miliana", "Miliana"), ("Mohammadia", "Mohammadia"), ("Mohammedia", "Mohammedia"), ("Mostaganem", "Mostaganem"), ("Mouadjebara", "Mouadjebara"), ("Mouzaïa", "Mouzaïa"),
    ("N'Gaous", "N'Gaous"), ("Nadorah", "Nadorah"), ("Negrine", "Negrine"), ("Nékmaria", "Nékmaria"), ("Nesmoth", "Nesmoth"), ("Nezla", "Nezla"), ("Oran", "Oran"), ("Ouadhia", "Ouadhia"),
    ("Ouaguenoun", "Ouaguenoun"), ("Ouargla", "Ouargla"), ("Ouarizane", "Ouarizane"), ("Oudjana", "Oudjana"), ("Oued Berkeche", "Oued Berkeche"), ("Oued Chorfa", "Oued Chorfa"), ("Oued Djemaa", "Oued Djemaa"),
    ("Oued Djer", "Oued Djer"), ("Oued El Ma", "Oued El Ma"), ("Oued Endja", "Oued Endja"), ("Oued Fodda", "Oued Fodda"), ("Oued Ghir", "Oued Ghir"), ("Oued Sebaa", "Oued Sebaa"), 
    ("Oued Seguen", "Oued Seguen"), ("Oued Sly", "Oued Sly"), ("Oued Taga", "Oued Taga"), ("Ouenza", "Ouenza"), ("Ouled Abbes", "Ouled Abbes"), ("Ouled Addi Guebala", "Ouled Addi Guebala"),
    ("Ouled Addouane", "Ouled Addouane"), ("Ouled Ahmed Timmi", "Ouled Ahmed Timmi"), ("Ouled Aissa", "Ouled Aissa"), ("Ouled Ammar", "Ouled Ammar"), ("Ouled Antar", "Ouled Antar"), 
    ("Ouled Aouf", "Ouled Aouf"), ("Ouled Atia", "Ouled Atia"), ("Ouled Attia", "Ouled Attia"), ("Ouled Ben Abdelkader", "Ouled Ben Abdelkader"), ("Ouled Bessem", "Ouled Bessem"),
    ("Ouled Bouachra", "Ouled Bouachra"), ("Ouled Boudjemaa", "Ouled Boudjemaa"), ("Ouled Boughalem", "Ouled Boughalem"), ("Ouled Brahem", "Ouled Brahem"), ("Ouled Brahim", "Ouled Brahim"),
    ("Ouled Chebel", "Ouled Chebel"), ("Ouled Dahmane", "Ouled Dahmane"), ("Ouled Derradj", "Ouled Derradj"), ("Ouled Djellal", "Ouled Djellal"), ("Ouled Driss", "Ouled Driss"), 
    ("Ouled Fadel", "Ouled Fadel"), ("Ouled Farès", "Ouled Farès"), ("Ouled Fayet", "Ouled Fayet"), ("Ouled Gacem", "Ouled Gacem"), ("Ouled Hamla", "Ouled Hamla"), ("Ouled Hedadj", "Ouled Hedadj"),
    ("Ouled Hellal", "Ouled Hellal"), ("Ouled Khaled", "Ouled Khaled"), ("Ouled Khoudir", "Ouled Khoudir"), ("Ouled Kihal", "Ouled Kihal"), ("Ouled Madhi", "Ouled Madhi"), ("Ouled Mansour", "Ouled Mansour"),
    ("Ouled Mimoun", "Ouled Mimoun"), ("Ouled Moumen", "Ouled Moumen"), ("Ouled Moussa", "Ouled Moussa"), ("Ouled Rabah", "Ouled Rabah"), ("Ouled Rached", "Ouled Rached"), ("Ouled Rahmoun", "Ouled Rahmoun"),
    ("Ouled Rechache", "Ouled Rechache"), ("Ouled Riyah", "Ouled Riyah"), ("Ouled Said", "Ouled Said"), ("Ouled Sassi", "Ouled Sassi"), ("Ouled Selama", "Ouled Selama"), ("Ouled Sellam", "Ouled Sellam"),
    ("Ouled Si Ahmed", "Ouled Si Ahmed"), ("Ouled Si Slimane", "Ouled Si Slimane"), ("Ouled Sidi Brahim", "Ouled Sidi Brahim"), ("Ouled Sidi Mihoub", "Ouled Sidi Mihoub"), ("Ouled Slimane", "Ouled Slimane"),
    ("Ouled Tebben", "Ouled Tebben"), ("Ouled Yahia Khedrouche", "Ouled Yahia Khedrouche"), ("Ouled Yaïch", "Ouled Yaïch"), ("Oulhaça El Gheraba", "Oulhaça El Gheraba"), ("Oultene", "Oultene"),
    ("Oum Ali", "Oum Ali"), ("Oum Drou", "Oum Drou"), ("Oum El Adhaim", "Oum El Adhaim"), ("Oum El Assel", "Oum El Assel"), ("Oum Laadham", "Oum Laadham"), ("Oum Toub", "Oum Toub"), ("Ourlala", "Ourlala"),
    ("Ourmes", "Ourmes"), ("Ouyoun El Assafir", "Ouyoun El Assafir"), ("Ouzellaguen", "Ouzellaguen"), ("Pigüé", "Pigüé"), ("Rabta", "Rabta"), ("Ragouba", "Ragouba"), ("Rahbat", "Rahbat"), 
    ("Rahmania", "Rahmania"), ("Rahouia", "Rahouia"), ("Ramdane Djamel", "Ramdane Djamel"), ("Ramka", "Ramka"), ("Raml Souk", "Raml Souk"), ("Raouraoua", "Raouraoua"), ("Ras El Agba", "Ras El Agba"),
    ("Ras El Aioun", "Ras El Aioun"), ("Ras El Oued", "Ras El Oued"), ("Rechaiga", "Rechaiga"), ("Redjem Demouche", "Redjem Demouche"), ("Reggane", "Reggane"), ("Reghaïa", "Reghaïa"), ("Reguiba", "Reguiba"),
    ("Relizane", "Relizane"), ("Remchi", "Remchi"), ("Remila", "Remila"), ("Ridane", "Ridane"), ("Robbah", "Robbah"), ("Rogassa", "Rogassa"), ("Roknia", "Roknia"), ("Rouïba", "Rouïba"), ("Rouina", "Rouina"),
    ("Sabra", "Sabra"), ("Safel El Ouiden", "Safel El Ouiden"), ("Saïda", "Saïda"), ("Salah Bey", "Salah Bey"), ("Salah Bouchaour", "Salah Bouchaour"), ("Sali", "Sali"), ("Saneg", "Saneg"), ("Saoula", "Saoula"),
    ("Sayada", "Sayada"), ("Sbaa", "Sbaa"), ("Sebaïne", "Sebaïne"), ("Sebdou", "Sebdou"), ("Sebgag", "Sebgag"), ("Sebt", "Sebt"), ("Seddouk", "Seddouk"), ("Sedjerara", "Sedjerara"), ("Seggana", "Seggana"),
    ("Seghouane", "Seghouane"), ("Sehailia", "Sehailia"), ("Sehala Thaoura", "Sehala Thaoura"), ("Selma Benziada", "Selma Benziada"), ("Selmana", "Selmana"), ("Semaoune", "Semaoune"), ("Sendjas", "Sendjas"),
    ("Sétif", "Sétif"), ("Settara", "Settara"), ("Sfissifa", "Sfissifa"), ("Si Abdelghani", "Si Abdelghani"), ("Si-Mustapha", "Si-Mustapha"), ("Sidi Abdelaziz", "Sidi Abdelaziz"),
    ("Sidi Abdeldjebar", "Sidi Abdeldjebar"), ("Sidi Abdellah", "Sidi Abdellah"), ("Sidi Abdelli", "Sidi Abdelli"), ("Sidi Abderrahmane", "Sidi Abderrahmane"), ("Sidi Aïch", "Sidi Aïch"),
    ("Sidi Aïssa", "Sidi Aïssa"), ("Sidi Akkacha", "Sidi Akkacha"), ("Sidi Ali", "Sidi Ali"), ("Sidi Ali Benyoub", "Sidi Ali Benyoub"), ("Sidi Ali Boussidi", "Sidi Ali Boussidi"),
    ("Sidi Ali Mellal", "Sidi Ali Mellal"), ("Sidi Amar", "Sidi Amar"), ("Sidi Ameur", "Sidi Ameur"), ("Sidi Aoun", "Sidi Aoun"), ("Sidi Baizid", "Sidi Baizid"), ("Sidi Bakhti", "Sidi Bakhti"),
    ("Sidi Bel Abbès", "Sidi Bel Abbès"), ("Sidi Ben Yebka", "Sidi Ben Yebka"), ("Sidi Boubekeur", "Sidi Boubekeur"), ("Sidi Boutouchent", "Sidi Boutouchent"), ("Sidi Brahim", "Sidi Brahim"),
    ("Sidi Djillali", "Sidi Djillali"), ("Sidi Fredj", "Sidi Fredj"), ("Sidi Hadjeres", "Sidi Hadjeres"), ("Sidi Hamadouche", "Sidi Hamadouche"), ("Sidi Khaled", "Sidi Khaled"), 
    ("Sidi Khouiled", "Sidi Khouiled"), ("Sidi Lahcene", "Sidi Lahcene"), ("Sidi Lakhdar", "Sidi Lakhdar"), ("Sidi Lantri", "Sidi Lantri"), ("Sidi Lazreg", "Sidi Lazreg"), ("Sidi M'Hamed", "Sidi M'Hamed"),
    ("Sidi Makhlouf", "Sidi Makhlouf"), ("Sidi Merouane", "Sidi Merouane"), ("Sidi Mezghiche", "Sidi Mezghiche"), ("Sidi Moussa", "Sidi Moussa"), ("Sidi Naamane", "Sidi Naamane"), 
    ("Sidi Ouriache", "Sidi Ouriache"), ("Sidi Rached", "Sidi Rached"), ("Sidi Saada", "Sidi Saada"), ("Sidi Safi", "Sidi Safi"), ("Sidi Semiane", "Sidi Semiane"), 
    ("Sidi Slimane (El Bayadh)", "Sidi Slimane (El Bayadh)"), ("Sidi Slimane (Ouargla)", "Sidi Slimane (Ouargla)"), ("Sidi Slimane (Tissemsilt)", "Sidi Slimane (Tissemsilt)"), 
    ("Sidi Yacoub", "Sidi Yacoub"), ("Sidi Zahar", "Sidi Zahar"), ("Sidi Ziane", "Sidi Ziane"), ("Sidi-Ayad", "Sidi-Ayad"), ("Sig", "Sig"), ("Sirat", "Sirat"), ("Skikda", "Skikda"), ("Sobha", "Sobha"),
    ("Souaflia", "Souaflia"), ("Souagui", "Souagui"), ("Souahlia", "Souahlia"), ("Souamaa", "Souamaa"), ("Souani", "Souani"), ("Souarekh", "Souarekh"), ("Sougueur", "Sougueur"), ("Souhane", "Souhane"),
    ("Souidania", "Souidania"), ("Souk Ahras", "Souk Ahras"), ("Souk El Had", "Souk El Had"), ("Souk El Khemis", "Souk El Khemis"), ("Souk El-Had", "Souk El-Had"), ("Souk El-Thenine", "Souk El-Thenine"),
    ("Souk Naamane", "Souk Naamane"), ("Souk-Oufella", "Souk-Oufella"), ("Soumaâ", "Soumaâ"), ("Sour El-Ghozlane", "Sour El-Ghozlane"), ("Stah Guentis", "Stah Guentis"), ("Staouéli", "Staouéli"),
    ("Stidia", "Stidia"), ("Stitten", "Stitten"), ("Tabelbala", "Tabelbala"), ("Tablat", "Tablat"), ("Tacheta Zougagha", "Tacheta Zougagha"), ("Tachouda", "Tachouda"), ("Tadjemout", "Tadjemout"),
    ("Tadjena", "Tadjena"), ("Tadjenanet", "Tadjenanet"), ("Tadjrouna", "Tadjrouna"), ("Tadmit", "Tadmit"), ("Tafissour", "Tafissour"), ("Tafraoui", "Tafraoui"), ("Tafreg", "Tafreg"), ("Tagdemt", "Tagdemt"),
    ("Taghit", "Taghit"), ("Taghzout (Bouïra)", "Taghzout (Bouïra)"), ("Taghzout (El Oued)", "Taghzout (El Oued)"), ("Taglait", "Taglait"), ("Taguedit", "Taguedit"), ("Taher", "Taher"), ("Taibet", "Taibet"),
    ("Takhemaret", "Takhemaret"), ("Tala Hamza", "Tala Hamza"), ("Talassa", "Talassa"), ("Taleb Larbi", "Taleb Larbi"), ("Talkhamt", "Talkhamt"), ("Talmine", "Talmine"), ("Tamacine", "Tamacine"),
    ("Tamalous", "Tamalous"), ("Tamanrasset", "Tamanrasset"), ("Tamentit", "Tamentit"), ("Tamesguida", "Tamesguida"), ("Tamest", "Tamest"), ("Tamlouka", "Tamlouka"), ("Tamokra", "Tamokra"),
    ("Tamridjet", "Tamridjet"), ("Tamsa", "Tamsa"), ("Tamtert", "Tamtert"), ("Tamza", "Tamza"), ("Tamzoura", "Tamzoura"), ("Taoudmout", "Taoudmout"), ("Taougrit", "Taougrit"), ("Taoura", "Taoura"),
    ("Taourga", "Taourga"), ("Taourirt Ighil", "Taourirt Ighil"), ("Tarik Ibn Ziad", "Tarik Ibn Ziad"), ("Tarmount", "Tarmount"), ("Taskriout", "Taskriout"), ("Taxlent", "Taxlent"), ("Taya", "Taya"),
    ("Tazgait", "Tazgait"), ("Tazmalt", "Tazmalt"), ("Tazrouk", "Tazrouk"), ("Tebesbest", "Tebesbest"), ("Tébessa", "Tébessa"), ("Telagh", "Telagh"), ("Teleghma", "Teleghma"), ("Timokten", "Timokten"),
    ("Touggourt", "Touggourt"),("Algiers",'Algiers'),("Blida","Blida")
)